### ISSUE TITLE
Can't run main file

### ISSUE THREAD

**Issue by mauro-balades** [ReCT-Lang/ReCT-Go-Compiler#15]
when I run `go run main.go` it gives an error.

```
# command-line-arguments
./main.go:16:2: undefined: Init
./main.go:18:2: undefined: ProcessFlags
note: module requires Go 1.16
```

maybe it is deprecated? It is fixed by running `go run cli.go`

**Comment by RedCubeDev-ByteSpace** [comment]
Try running `go run .` to run the entire package

**Comment by tokorv** [comment]
You usually don’t want to run the entire package, usually you will want to build it so you can run the flags on your own.

You can use `go build -v -o rgoc .` to create the executable and then run `./rgoc` to see usages.

**Comment by RedCubeDev-ByteSpace** [comment]
you cant run a single source file
you need to run the entire project otherwise it wont work
`go run .` in the projects directory...

**Comment by mauro-balades** [comment]
Oh... Ok
