### ISSUE TITLE
ISSUE COMMENT PINS

### ISSUE THREAD

**Issue by Khhs167** [ReCT-Lang/ReCT-Go-Compiler#25]
i dunno man this is like doing tech support over telephone
absolutely no clue whats going on

_Originally posted by @RedCubeDev-ByteSpace in https://github.com/ReCT-Lang/ReCT-Go-Compiler/issues/10#issuecomment-1221417426_

**Comment by Khhs167** [comment]
All comments in here will be removed

**Comment by mauro-balades** [comment]
hm

**Comment by mr-cheffy** [comment]
close this pls
