### ISSUE TITLE
Terrible method to store rect packages

### ISSUE THREAD

**Issue by mauro-balades** [ReCT-Lang/ReCT-Go-Compiler#28]
Currently, rect packages are stored into `[PATH Of EXECUTABLE]/packages/*`. This is a terrible way of keeping them because when the user installs rgoc, they would normally install it into `/usr/bin` or `/usr/local/bin`. This means that the packages would need to be stored at `/usr/bin/packages/*`. The bin folder should NOT contain anything else except for the user programs. 

What are some possible solutions?
* One solution that I thought was that packages should be installed into `/usr/lib/rect`. The installer could change this location and it could be added to the user `$PATH`.

Another issue is that the user may need different versions of the same package for different projects. This is an issue that python3 had and the solution was basically doing a virtual environment for every project and storing the packages locally to that project instead of globally. Or you could do it the nodeJS way and it's to install them into a `rect_packages?` folder.

**Comment by Khhs167** [comment]
Readding my idea from the discord.

**PROBLEM**: Package root dir is forced globally, and local packs are only available with full path
**SOLUTION**:
We add something like a `-p`/`--package-dir` flag, that allows the user to specify the directory that rgoc should search in for the global dir. By default this would be set to `$EXE_DIR/packages`, but then the user can change it to, let's say `$HOME/.packages`, using `--package-dir $HOME/.packages` or `-p $HOME/.packages`.

**Comment by RedCubeDev-ByteSpace** [comment]
Will consider :+1:

**Comment by mauro-balades** [comment]
> Currently, rect packages are stored into `[PATH Of EXECUTABLE]/packages/*`. This is a terrible way of keeping them because when the user installs rgoc, they would normally install it into `/usr/bin` or `/usr/local/bin`. This means that the packages would need to be stored at `/usr/bin/packages/*`. The bin folder should NOT contain anything else except for the user programs.

yea, (just to make it clear) my main issue is this:
> Currently, rect packages are stored into [PATH Of EXECUTABLE]/packages/*. This is a terrible way of keeping them because when the user installs rgoc, they would normally install it into /usr/bin or /usr/local/bin. This means that the packages would need to be stored at /usr/bin/packages/*. The bin folder should NOT contain anything else except for the user programs.

**Comment by mr-cheffy** [comment]
imma just close this. I dont even code anymore. Some times I wanna fucking die and I delve in these non sensical delusions to make the hurt go away for a few minutes. It helps. Not in the long term but it helps. Nothing will ever change I will forever be subject to this never ending purgatory of which is known as life. I do not know why I am here and why I am still here or why I have chosen not to leave. All I know is that I am here. Nothing has changed as a result of my presence. Why bother. Sometimes I wonder this. But in the end these delusions often help me get through my day as they inspire me to actually work and give me a false sense of hope that things will get better and everything will be fine. But it all gets shattered the moment when reality hits you. The fact that you are not as useful as others and that your purpose is just to be here and nothing else.
